// The report's page plan: which page holds what. Pure (no library, no I/O), so the PDF and the
// PowerPoint are guaranteed to say the same things in the same order, and so it can be tested.
//
// Units are points. The two renderers hand in their own page size; everything else follows from it.
// A main task and its discipline tasks are never split across pages, and a heading is never left
// alone at the bottom of a page.

import { reportDate, type ReportData, type ReportLateItem, type ReportMissingDoc, type ReportTimelineDiscipline, type ReportTimelineMainTask } from "@/server/services/report";

export type Geometry = {
  pageW: number;
  pageH: number;
  margin: number;
  /** Body and table text size: 12 in the PDF, 14 in the PowerPoint. */
  bodyFont: number;
};

/** Most discipline bars shown under one main task; the rest are "+N more". */
export const MAX_DISCIPLINE_BARS = 6;

export const FOOTER_TEXT = (data: ReportData): string =>
  `Generated by Tielora from live project data on ${reportDate(data.generatedAt)}.`;

const plural = (n: number, one: string, many = `${one}s`): string => `${n} ${n === 1 ? one : many}`;

/** The one line on the cover: both late kinds named, zeros kept. */
export function coverLine(data: ReportData): string {
  return (
    `${plural(data.late.main, "main task")} and ${plural(data.late.discipline, "discipline task")} late` +
    ` · ${data.blocked} blocked · ${data.documents.missing} required ${data.documents.missing === 1 ? "document" : "documents"} missing`
  );
}

/** "Construction is locked, waiting on FEED, which still has 9 main tasks open." */
export function lockedSentence(phase: { name: string; waitingOn: string | null; openTaskCount: number }): string {
  return `${phase.name} is locked, waiting on ${phase.waitingOn ?? "earlier work"}, which still has ${plural(phase.openTaskCount, "main task")} open.`;
}

export function daysLateText(days: number): string {
  return `${days} d`;
}

/* ------------------------------------------------------------------ */
/* Page plan                                                           */
/* ------------------------------------------------------------------ */

/** Space every content page gives its body: below the title rule, above the footer. */
export const TITLE_BLOCK_H = 52;
export const FOOTER_H = 30;

export function bodyHeight(geo: Geometry): number {
  return geo.pageH - geo.margin - TITLE_BLOCK_H - geo.margin / 2 - FOOTER_H + 12;
}

export type TimelineBlock = {
  task: ReportTimelineMainTask;
  shown: ReportTimelineDiscipline[];
  moreDisciplines: number;
  /** The phase band this row sits in (index into the band sequence), and its name (null when the project has no phases). */
  band: number;
  bandName: string | null;
  /** Set by pagination on the first row of a band on each page; the band's name is written there. */
  bandLabel: string | null;
  h: number;
};

export type FlowItem =
  | { kind: "heading"; text: string; h: number; keep: number }
  | { kind: "text"; text: string; h: number; keep: number }
  | { kind: "card"; title: string; assignee: string; blockers: { title: string; assignee: string }[]; h: number; keep: number }
  | { kind: "docSummary"; inPlace: number; required: number; h: number; keep: number }
  | { kind: "tableHeader"; cols: string[]; h: number; keep: number }
  | { kind: "discRow"; code: string; inPlace: number; required: number; h: number; keep: number; repeat?: FlowItem }
  | { kind: "missingRow"; doc: ReportMissingDoc; h: number; keep: number; repeat?: FlowItem };

export type PagePlan =
  | { kind: "cover" }
  | { kind: "timeline"; title: string; blocks: TimelineBlock[]; moreNote: string | null; empty: boolean }
  | { kind: "late"; title: string; rows: ReportLateItem[]; empty: boolean }
  | { kind: "flow"; title: string; items: FlowItem[] };

export const BAND_LABEL_H = 12;
export const TIMELINE_AXIS_H = 30;
export const TIMELINE_LEGEND_H = 26;
export const TABLE_HEADER_H = 26;

export function tableRowH(geo: Geometry): number {
  return Math.round(geo.bodyFont * 2);
}
export function timelineRowH(geo: Geometry): number {
  return Math.round(geo.bodyFont * 1.7);
}
export function timelineSubH(geo: Geometry): number {
  return Math.max(13, Math.round(geo.bodyFont * 1.1));
}

/** Splits flow items into pages without splitting an item, honouring `keep` and repeating table headers. */
export function paginateFlow(items: FlowItem[], capacity: number): FlowItem[][] {
  const pages: FlowItem[][] = [];
  let page: FlowItem[] = [];
  let used = 0;

  const push = (item: FlowItem) => {
    page.push(item);
    used += item.h;
  };

  for (let i = 0; i < items.length; i += 1) {
    const item = items[i];
    let need = item.h;
    for (let k = 1; k <= item.keep && i + k < items.length; k += 1) need += items[i + k].h;
    if (page.length > 0 && used + need > capacity) {
      pages.push(page);
      page = [];
      used = 0;
    }
    if (page.length === 0 && "repeat" in item && item.repeat) push(item.repeat);
    push(item);
  }
  if (page.length > 0) pages.push(page);
  return pages;
}

/** Cuts a timeline's blocks into pages. A block is never split; every page fits at least one. */
export function paginateTimeline(blocks: TimelineBlock[], capacity: number): TimelineBlock[][] {
  const pages: TimelineBlock[][] = [];
  let page: TimelineBlock[] = [];
  let used = 0;
  let lastBand = -1;
  for (const block of blocks) {
    const labelH = (startsBand: boolean) => (startsBand && block.bandName !== null ? BAND_LABEL_H : 0);
    if (page.length > 0 && used + block.h + labelH(block.band !== lastBand) > capacity) {
      pages.push(page);
      page = [];
      used = 0;
      lastBand = -1;
    }
    // The first row of a band on a page carries the band's name (even when the band began earlier).
    const startsBand = page.length === 0 || block.band !== lastBand;
    const extra = labelH(startsBand);
    page.push({ ...block, bandLabel: startsBand ? block.bandName : null, h: block.h + extra });
    used += block.h + extra;
    lastBand = block.band;
  }
  if (page.length > 0) pages.push(page);
  return pages;
}

export function planReport(data: ReportData, geo: Geometry): PagePlan[] {
  const plans: PagePlan[] = [{ kind: "cover" }];
  const body = bodyHeight(geo);
  const rowH = tableRowH(geo);

  /* ---- timeline ---- */
  const tl = data.timeline;
  if (tl.mainTasks.length === 0) {
    plans.push({ kind: "timeline", title: "Timeline snapshot", blocks: [], moreNote: null, empty: true });
  } else {
    const hasBands = tl.phases.length > 0;
    const phaseName = new Map(tl.phases.map((phase) => [phase.id, phase.name]));
    const mainH = timelineRowH(geo);
    const subH = timelineSubH(geo);

    // Band sequence: consecutive rows with the same phase form one band.
    const blocks: TimelineBlock[] = [];
    let band = -1;
    let lastPhase: string | null | undefined;
    for (const task of tl.mainTasks) {
      if (band < 0 || task.phaseId !== lastPhase) band += 1;
      lastPhase = task.phaseId;
      const name = hasBands ? (task.phaseId ? (phaseName.get(task.phaseId) ?? "") : "No phase") : null;
      const shown = task.disciplineTasks.slice(0, MAX_DISCIPLINE_BARS);
      const more = task.disciplineTasks.length - shown.length;
      const h = mainH + shown.length * subH + (more > 0 ? subH : 0) + 4;
      blocks.push({ task, shown, moreDisciplines: more, band, bandName: name, bandLabel: null, h });
    }
    const moreNote =
      tl.moreMainTasks > 0
        ? `and ${plural(tl.moreMainTasks, "more main task")} (all are counted in the numbers)`
        : null;
    const capacity = body - TIMELINE_AXIS_H - TIMELINE_LEGEND_H - (moreNote ? 18 : 0);
    const pages = paginateTimeline(blocks, capacity);
    pages.forEach((pageBlocks, index) => {
      plans.push({
        kind: "timeline",
        title: pages.length === 1 ? "Timeline snapshot" : `Timeline snapshot (${index + 1} of ${pages.length})`,
        blocks: pageBlocks,
        // The "and N more" line sits below the last drawn row, so only the last page carries it.
        moreNote: index === pages.length - 1 ? moreNote : null,
        empty: false,
      });
    });
  }

  /* ---- what is late ---- */
  const lateTitle = `What is late (${data.lateItems.length})`;
  if (data.lateItems.length === 0) {
    plans.push({ kind: "late", title: lateTitle, rows: [], empty: true });
  } else {
    const perPage = Math.max(1, Math.floor((body - TABLE_HEADER_H) / rowH));
    for (let i = 0; i < data.lateItems.length; i += perPage) {
      plans.push({
        kind: "late",
        title: i === 0 ? lateTitle : `${lateTitle} — continued`,
        rows: data.lateItems.slice(i, i + perPage),
        empty: false,
      });
    }
  }

  /* ---- who is blocking ---- */
  const lineH = Math.round(geo.bodyFont * 1.4);
  const flow: FlowItem[] = [];
  if (data.blockedTasks.length > 0) {
    flow.push({ kind: "heading", text: `Blocked tasks (${data.blocked})`, h: 36, keep: 1 });
    for (const task of data.blockedTasks) {
      const blockers = task.blockedBy.map((entry) => ({
        title: entry.title,
        assignee: entry.assigneeName ?? "Not assigned",
      }));
      const lines = 2 + Math.max(1, blockers.length);
      flow.push({
        kind: "card",
        title: task.title,
        assignee: task.assigneeName ?? "Not assigned",
        blockers,
        h: lines * lineH + 18,
        keep: 0,
      });
    }
    if (data.blockedMore > 0) {
      flow.push({ kind: "text", text: `and ${plural(data.blockedMore, "more blocked task")}`, h: 22, keep: 0 });
    }
  }
  if (data.lockedPhases.length > 0) {
    flow.push({ kind: "heading", text: "Locked phases", h: 36, keep: 1 });
    for (const phase of data.lockedPhases) {
      flow.push({ kind: "text", text: lockedSentence(phase), h: lineH + 8, keep: 0 });
    }
  }
  if (flow.length === 0) {
    flow.push({ kind: "text", text: "Nothing is blocked right now.", h: 28, keep: 0 });
  }
  paginateFlow(flow, body).forEach((items, index) => {
    plans.push({ kind: "flow", title: index === 0 ? "Who is blocking" : "Who is blocking — continued", items });
  });

  /* ---- documents ---- */
  const docs = data.documents;
  const docFlow: FlowItem[] = [
    { kind: "docSummary", inPlace: docs.inPlace, required: docs.required, h: 64, keep: 2 },
  ];
  if (docs.byDiscipline.length > 0) {
    const header: FlowItem = { kind: "tableHeader", cols: ["Discipline", "In place / required", ""], h: TABLE_HEADER_H, keep: 1 };
    docFlow.push(header);
    for (const row of docs.byDiscipline) {
      docFlow.push({
        kind: "discRow",
        code: row.disciplineCode,
        inPlace: row.inPlace,
        required: row.required,
        h: rowH,
        keep: 0,
        repeat: header,
      });
    }
  }
  if (docs.missing === 0) {
    docFlow.push({ kind: "text", text: "All required documents are in place.", h: 28, keep: 0 });
  } else {
    docFlow.push({ kind: "heading", text: `Missing (${docs.missing})`, h: 36, keep: 2 });
    const header: FlowItem = {
      kind: "tableHeader",
      cols: ["Document", "Task", "Discipline", "Assigned to"],
      h: TABLE_HEADER_H,
      keep: 1,
    };
    docFlow.push(header);
    for (const doc of docs.missingList) {
      docFlow.push({ kind: "missingRow", doc, h: rowH, keep: 0, repeat: header });
    }
    if (docs.missingMore > 0) {
      docFlow.push({ kind: "text", text: `and ${docs.missingMore} more`, h: 22, keep: 0 });
    }
  }
  paginateFlow(docFlow, body).forEach((items, index) => {
    plans.push({ kind: "flow", title: index === 0 ? "Documents" : "Documents — continued", items });
  });

  return plans;
}

/* ------------------------------------------------------------------ */
/* Timeline scale, shared by both drawings                             */
/* ------------------------------------------------------------------ */

export type MonthTick = { at: number; label: string | null };

/**
 * Month lines across [start, end], as fractions 0..1 of the width, with a label on the first month
 * and on every January ("Sep 2026"; others "Oct"). Dense scales label only every 2nd/3rd/6th month.
 */
export function monthTicks(start: Date, end: Date, widthPt: number): MonthTick[] {
  const span = Math.max(1, end.getTime() - start.getTime());
  const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  const first = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth(), 1));
  const months: Date[] = [];
  for (let d = first; d.getTime() <= end.getTime(); d = new Date(Date.UTC(d.getUTCFullYear(), d.getUTCMonth() + 1, 1))) {
    months.push(d);
    if (months.length > 240) break;
  }
  const perMonth = widthPt / Math.max(1, months.length);
  const step = perMonth >= 44 ? 1 : perMonth >= 22 ? 2 : perMonth >= 14 ? 3 : 6;
  const ticks: MonthTick[] = [];
  let lastYear: number | null = null;
  months.forEach((date, index) => {
    if (index % step !== 0) return;
    // The year goes on the first label and wherever the year changes (so every January is marked,
    // even when a crowded scale skips the month itself).
    const year = date.getUTCFullYear();
    const withYear = lastYear === null || year !== lastYear || date.getUTCMonth() === 0;
    lastYear = year;
    ticks.push({
      at: (date.getTime() - start.getTime()) / span,
      label: withYear ? `${MONTHS[date.getUTCMonth()]} ${year}` : MONTHS[date.getUTCMonth()],
    });
  });
  return ticks;
}

/** The drawn scale: whole months, so every tick sits inside it. Null when there is nothing to draw. */
export function axisRange(data: ReportData): { start: Date; end: Date } | null {
  const { rangeStart, rangeEnd } = data.timeline;
  if (!rangeStart || !rangeEnd) return null;
  const start = new Date(Date.UTC(rangeStart.getUTCFullYear(), rangeStart.getUTCMonth(), 1));
  const end = new Date(Date.UTC(rangeEnd.getUTCFullYear(), rangeEnd.getUTCMonth() + 1, 1));
  return { start, end };
}
