// The Teams single-sign-on token is checked like a bank cheque. Every token here is REALLY signed
// with an RSA key generated by the test and published by a fake Microsoft behind `global.fetch`, so
// every check the validator makes is made for real. No network is ever touched, and the fetch mock
// also proves the only host ever asked for keys is login.microsoftonline.com.

import { createHmac } from "node:crypto";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import {
  JwksCache,
  TEAMS_CLIENT_IDS,
  validateTeamsToken,
  type KeyLookup,
} from "@/lib/ms-id-token";
import { fetchSigningKeys } from "@/server/services/graph";
import {
  TEST_CLIENT_ID,
  installFakeMicrosoft,
  makeKey,
  newOid,
  newTenant,
  signToken,
  teamsClaimsFor,
  type FakeMicrosoft,
} from "@/server/__tests__/microsoft-signin-fixtures";

const KEY = makeKey("kid-teams");
const EXPECT = { audience: TEST_CLIENT_ID };

let fake: FakeMicrosoft;
let clock = 1_800_000_000_000;
let cache: JwksCache;
let keys: KeyLookup;

beforeEach(() => {
  fake = installFakeMicrosoft([KEY.jwk]);
  clock = 1_800_000_000_000;
  cache = new JwksCache(fetchSigningKeys, () => clock);
  keys = cache.keyFor;
});

afterEach(() => {
  vi.restoreAllMocks();
});

function good(overrides: Record<string, unknown> = {}) {
  const tid = newTenant();
  const oid = newOid();
  return { tid, oid, claims: { ...teamsClaimsFor({ tid, oid, now: clock }), ...overrides } };
}

async function check(token: string) {
  return validateTeamsToken(token, { ...EXPECT, now: clock }, keys);
}

describe("a Teams token", () => {
  it("is accepted when everything is right — and carries only the tenant and the object id", async () => {
    const { tid, oid, claims } = good({ email: "someone@contoso.example" });
    const result = await check(signToken(claims, KEY));

    expect(result).toEqual({ ok: true, identity: { tid, oid } });
    // The token has no reliable verified email, so none is ever handed on.
    expect(JSON.stringify(result)).not.toContain("contoso");
  });

  it("is refused when it has expired (past the two minutes of tolerance)", async () => {
    const { claims } = good({ exp: Math.floor(clock / 1000) - 600 });
    expect(await check(signToken(claims, KEY))).toEqual({ ok: false, reason: "expired" });
  });

  it("is refused when it is not valid yet", async () => {
    const { claims } = good({ nbf: Math.floor(clock / 1000) + 3600 });
    expect(await check(signToken(claims, KEY))).toEqual({ ok: false, reason: "not-yet-valid" });
  });

  it("is refused for the wrong audience — including the other spelling of the right one", async () => {
    const other = good({ aud: "00000000-0000-0000-0000-000000000000" });
    expect(await check(signToken(other.claims, KEY))).toEqual({ ok: false, reason: "wrong-audience" });

    // Only ONE audience is ever accepted: the api:// address is refused while the client id is pinned.
    const address = good({ aud: `api://tielora.test/${TEST_CLIENT_ID}` });
    expect(await check(signToken(address.claims, KEY))).toEqual({ ok: false, reason: "wrong-audience" });
  });

  it("is refused when the issuer's tenant is not the token's own tenant", async () => {
    const { claims } = good({ iss: `https://login.microsoftonline.com/${newTenant()}/v2.0` });
    expect(await check(signToken(claims, KEY))).toEqual({ ok: false, reason: "wrong-issuer" });
  });

  it("is refused for a version-1 issuer", async () => {
    const { tid, claims } = good();
    const v1 = { ...claims, iss: `https://sts.windows.net/${tid}/` };
    expect(await check(signToken(v1, KEY))).toEqual({ ok: false, reason: "wrong-issuer" });
  });

  it("is refused with the wrong signature (a different key under the same key id)", async () => {
    const forger = makeKey("kid-teams");
    const { claims } = good();
    expect(await check(signToken(claims, forger))).toEqual({ ok: false, reason: "bad-signature" });
  });

  it("is refused for a key id Microsoft does not publish", async () => {
    const stranger = makeKey("kid-nobody-published");
    const { claims } = good();
    expect(await check(signToken(claims, stranger))).toEqual({ ok: false, reason: "unknown-key" });
  });

  it("is refused with alg none", async () => {
    const { claims } = good();
    const head = Buffer.from(JSON.stringify({ alg: "none", typ: "JWT", kid: KEY.kid })).toString("base64url");
    const body = Buffer.from(JSON.stringify(claims)).toString("base64url");
    expect(await check(`${head}.${body}.AAAA`)).toEqual({ ok: false, reason: "unsupported-algorithm" });
  });

  it("is refused when signed with a shared secret that is Microsoft's public key (algorithm confusion)", async () => {
    const { claims } = good();
    const head = Buffer.from(JSON.stringify({ alg: "HS256", typ: "JWT", kid: KEY.kid })).toString("base64url");
    const body = Buffer.from(JSON.stringify(claims)).toString("base64url");
    const publicPem = JSON.stringify(KEY.jwk);
    const signature = createHmac("sha256", publicPem).update(`${head}.${body}`).digest("base64url");
    expect(await check(`${head}.${body}.${signature}`)).toEqual({ ok: false, reason: "unsupported-algorithm" });
  });

  it("is refused without the access_as_user scope", async () => {
    const none = good({ scp: undefined });
    expect(await check(signToken(none.claims, KEY))).toEqual({ ok: false, reason: "wrong-scope" });
    const wrong = good({ scp: "User.Read" });
    expect(await check(signToken(wrong.claims, KEY))).toEqual({ ok: false, reason: "wrong-scope" });
  });

  it("is accepted when access_as_user is one of several granted scopes", async () => {
    const { claims } = good({ scp: "User.Read access_as_user" });
    expect((await check(signToken(claims, KEY))).ok).toBe(true);
  });

  it("is refused from a calling client that is not one of the two Teams clients", async () => {
    const { claims } = good({ azp: "00000000-1111-2222-3333-444444444444" });
    expect(await check(signToken(claims, KEY))).toEqual({ ok: false, reason: "unknown-client" });
    const missing = good({ azp: undefined });
    expect(await check(signToken(missing.claims, KEY))).toEqual({ ok: false, reason: "unknown-client" });
  });

  it("accepts both listed Teams clients", async () => {
    expect(TEAMS_CLIENT_IDS).toHaveLength(2);
    for (const azp of TEAMS_CLIENT_IDS) {
      const { claims } = good({ azp });
      expect((await check(signToken(claims, KEY))).ok).toBe(true);
    }
  });

  it("is refused without an oid or without a tid", async () => {
    const noOid = good({ oid: undefined });
    expect(await check(signToken(noOid.claims, KEY))).toEqual({ ok: false, reason: "missing-oid" });
    const noTid = good({ tid: undefined });
    expect(await check(signToken(noTid.claims, KEY))).toEqual({ ok: false, reason: "bad-tenant" });
  });

  it("is refused from Microsoft's personal-account tenant", async () => {
    const personal = "9188040d-6c67-4c5b-b112-36a304b66dad";
    const { claims } = good({ tid: personal, iss: `https://login.microsoftonline.com/${personal}/v2.0` });
    expect(await check(signToken(claims, KEY))).toEqual({ ok: false, reason: "personal-account" });
  });

  it("is refused when it is not a token at all", async () => {
    expect(await check("not-a-token")).toEqual({ ok: false, reason: "malformed" });
    expect(await check("a.b.c")).toEqual({ ok: false, reason: "malformed" });
    expect(await check("x".repeat(20_000))).toEqual({ ok: false, reason: "malformed" });
  });
});

describe("Microsoft's signing keys, for the Teams token", () => {
  it("refuses, and throws nothing, when Microsoft cannot be reached", async () => {
    vi.restoreAllMocks();
    vi.spyOn(globalThis, "fetch").mockRejectedValue(new Error("network down"));
    const { claims } = good();
    await expect(check(signToken(claims, KEY))).resolves.toEqual({ ok: false, reason: "unknown-key" });
  });

  it("refuses when Microsoft answers with an error", async () => {
    fake.keys = [];
    const { claims } = good();
    expect(await check(signToken(claims, KEY))).toEqual({ ok: false, reason: "unknown-key" });
  });

  it("does not fetch again for a second good token", async () => {
    const first = good();
    const second = good();
    expect((await check(signToken(first.claims, KEY))).ok).toBe(true);
    expect((await check(signToken(second.claims, KEY))).ok).toBe(true);
    expect(fake.jwksCalls).toBe(1);
  });

  it("fetches at most once in a minute however many made-up key ids arrive", async () => {
    // One good token first, so the key set is loaded.
    expect((await check(signToken(good().claims, KEY))).ok).toBe(true);
    expect(fake.jwksCalls).toBe(1);

    for (let index = 0; index < 10; index += 1) {
      const stranger = makeKey(`kid-made-up-${index}`);
      expect(await check(signToken(good().claims, stranger))).toEqual({ ok: false, reason: "unknown-key" });
    }
    // Inside the first minute an unknown key id buys no early re-fetch at all.
    expect(fake.jwksCalls).toBe(1);

    // After the minute, ten more still cost exactly one re-fetch between them.
    clock += 61_000;
    for (let index = 10; index < 20; index += 1) {
      const stranger = makeKey(`kid-made-up-${index}`);
      await check(signToken(good().claims, stranger));
    }
    expect(fake.jwksCalls).toBe(2);
  });

  it("only ever asks login.microsoftonline.com", async () => {
    await check(signToken(good().claims, KEY));
    const hosts = vi
      .mocked(globalThis.fetch)
      .mock.calls.map(([input]) => new URL(String(input instanceof Request ? input.url : input)).host);
    expect(hosts.length).toBeGreaterThan(0);
    expect(new Set(hosts)).toEqual(new Set(["login.microsoftonline.com"]));
    expect(fake.otherCalls).toEqual([]);
  });
});
